### PR TITLE
Add test of performance for bash completion

### PR DESCRIPTION
**Pull request by marckhouzam**
The bash completion v2 script is currently very slow.  These tests will help prevent a regression once we've improved the v2 script.

See https://github.com/spf13/cobra/issues/1680

I'll wait until we have improved the script before merging.

### CODE REVIEW

**Comment by scop** [comment]
Very nice :+1:. I'd suggest adding something providing benchmarkability also for completions without descriptions, because the code paths and optimization opportunities may differ. For example a command line boolean flag to `manycomps` and respective test suite uses.

Perhaps also a "mixed" mode test where some completion candidates have descriptions and some don't. This isn't terribly interesting in benchmark sense, but would be good to verify that the case works, too. In that sense also perhaps out of scope for this PR.

**Comment by marckhouzam** [comment]
> Very nice 👍. I'd suggest adding something providing benchmarkability also for completions without descriptions, because the code paths and optimization opportunities may differ. For example a command line boolean flag to `manycomps` and respective test suite uses.

As you later noticed the test suite runs test without descriptions and with descriptions 👍 

> Perhaps also a "mixed" mode test where some completion candidates have descriptions and some don't. This isn't terribly interesting in benchmark sense, but would be good to verify that the case works, too. In that sense also perhaps out of scope for this PR.

I agree, out of scope for this PR, but the idea is not without merit.

**Comment by marckhouzam** [comment]
The optimizations made by @scop to the bash v2 script has allowed me to lower the limits within this PR to:
- 0.2 seconds for 1000 completions without descriptions
- 0.5 seconds for 1000 completions with descriptions

And we have room to spare.

Thanks @scop 💥

**Comment by marckhouzam** [comment]
I had left an 'exit' in the PR which I had added just to speed up my tests.
I have removed it here https://github.com/marckhouzam/cobra-completion-testing/commit/9b537b1408e3830bc845fb96afc8b9348ec7960c

That's what happens when there is no code review 😄

**Pull request merged**
